name: Outputs Demo

on:
  push

jobs:

  build:
    runs-on: ubuntu-latest

    outputs:
      app_name: ${{ steps.setvalue.outputs.app_name }}

    steps:

      - name: Set Output
        id: setvalue

        run: |
          echo "app_name=Portfolio" >> $GITHUB_OUTPUT

  deploy:
    runs-on: ubuntu-latest

    needs: build

    steps:

      - name: Read Output

        run: |
          echo "${{ needs.build.outputs.app_name }}"
