name: Expressions & Context Demo

on:
  workflow_dispatch:

jobs:
  demo:
    runs-on: ubuntu-latest

    steps:
      - name: Print Actor
        run: echo "${{ github.actor }}"

      - name: Print Repository
        run: echo "${{ github.repository }}"

      - name: Print Branch
        run: echo "${{ github.ref }}"

      - name: Print Event
        run: echo "${{ github.event_name }}"

      - name: Run only on Main Branch
        if: ${{ github.ref == 'refs/heads/main' }}
        run: echo "Running on Main Branch"

      - name: Run only for Krishna
        if: ${{ github.actor == 'kriish2002' }}
        run: echo "Hello Krishna"

      - name: Run on Main OR Manual Trigger
        if: ${{ github.ref == 'refs/heads/main' || github.event_name == 'workflow_dispatch' }}
        run: echo "OR Condition Passed"

      - name: Run on Main AND Krishna
        if: ${{ github.ref == 'refs/heads/main' && github.actor == 'kriish2002' }}
        run: echo "AND Condition Passed"